# SKLearn 04 | Data Preprocessing dengan Scikit-Learn | Belajar Machine Learning Dasar

Link Youtube : https://www.youtube.com/watch?v=smNnhEd26Ek

## Sample Data

In [2]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5],
                        [-1.5, 2.4, 3.5],
                        [0.5, -7.9, 5.6],
                        [5.0, 2.3, -5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5. ,  2.3, -5.8]])

In [3]:
sample_data.shape

(4, 3)

## Binarisation

In [5]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5. ,  2.3, -5.8]])

In [8]:
preprocessor = preprocessing.Binarizer (threshold = 0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

## Scaling

In [7]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5. ,  2.3, -5.8]])

In [10]:
preprocessor = preprocessing.MinMaxScaler (feature_range = (0,1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.55384615, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.30769231, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [12]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.55384615, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.30769231, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

## L1 Normalisation: Least Absolute Devitions

In [13]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5. ,  2.3, -5.8]])

In [14]:
l1_normalised_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalised_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.38167939,  0.17557252, -0.44274809]])

## L2 Normalisation: Least Squares

In [15]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5. ,  2.3, -5.8]])

In [16]:
l2_normalised_data = preprocessing.normalize(sample_data, norm='l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.62534208,  0.28765736, -0.72539681]])